version: "3.8"

services:
  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: greeting
      MYSQL_DATABASE: take365
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    command: [mysqld, "--default-authentication-plugin=mysql_native_password"]
volumes:
  mysql:
