<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2016-06-09 17:18:18
 */
return [
    'app' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'js/app-5733cac4e00f7210b480478b1a27922d.js',
        ],
        'css' => [
            'css/app-9e0923065f234d972d6f6cc9c2faa57d.css',
        ],
    ],
    'front' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'js/front-231f487e116d2114e649d65918bd3ffe.js',
        ],
        'css' => [
            'css/front-17e2d85462f630aa21714e2b4b8c5c6c.css',
        ],
    ],
    'profile' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'js/profile-913ff24eadf34273b78ccb63c29e57e2.js',
        ],
        'css' => [
            'css/profile-de8a9e66dbe275a60aa054399c39a90d.css',
        ],
    ],
    'recover' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'js/recover-bf0de58c5461bb1f2737855c145ba68d.js',
        ],
        'css' => [],
    ],
    'story' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'js/story-5b938c80528c629e483bb899f948c73f.js',
        ],
        'css' => [
            'css/app-871751030bed9f987e549de6dea558b2.css',
        ],
    ],
    'jquery' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/min',
        'baseUrl' => '@web/min',
        'js' => [
            'js/jquery-adc7d1917b7000d412ee27a72f6f11b9.js',
        ],
        'css' => [],
    ],
    'app\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\JqueryAsset',
            'app',
        ],
    ],
    'app\\assets\\FrontAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'front',
        ],
    ],
    'app\\assets\\ProfileAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'profile',
        ],
    ],
    'app\\assets\\RecoverAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AppAsset',
            'recover',
        ],
    ],
    'app\\assets\\StoryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AppAsset',
            'story',
        ],
    ],
    'app\\assets\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'jquery',
        ],
    ],
];