<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2016-01-22 17:26:21
 */
return [
    'app' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'js.min/app-186ab0c22a9a8b65baef08f2409fef06.js',
        ],
        'css' => [
            'css.min/app-9bd85f4f587c09c47bc3a5ed872cbf2d.css',
        ],
    ],
    'app\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app',
        ],
    ],
];